	org 12288
; Sound Effects for song , version 2.0, generated by Arkos Tracker 2.

SoundEffects
SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
SoundEffectsDisarkPointerRegionStart0
	dw SoundEffects_Sound1	; Sound effect 1.
	dw SoundEffects_Sound2	; Sound effect 2.
	dw 0	; Sound effect 3.
	dw 0	; Sound effect 4.
SoundEffectsDisarkPointerRegionEnd0

SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
SoundEffects_Sound1
	db 0	; Speed

SoundEffects_Sound1_Loop	db 61	; Soft only. Volume: 15.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 80	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 119	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 80	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 60	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 119	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 80	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 60	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 119	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 80	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 60	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 119	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 80	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 60	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 119	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 80	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 60	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 119	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 80	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 60	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 119	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 80	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 60	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 119	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 80	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 60	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 119	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
SoundEffects_Sound2
	db 0	; Speed

SoundEffects_Sound2_Loop	db 189	; Soft only. Volume: 15.
	db 2	; Noise: 2.
	dw 478	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 956	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 478	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 1911	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 478	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 239	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 956	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 478	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 1911	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 478	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 239	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 956	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 478	; Software period.

	db 4	; End of the sound effect.

SoundEffectsDisarkByteRegionEnd1
